export const productList = [
  {
    id: 1,
    idTag: "USAGUJ",
    name: "ANTHRACITE PERU",
    icon: <i class="devicon-react-original colored"></i>,
    country: "Peru",
    weight: "10382GAD(Kcal/Kg)",
    buy: "Best Buyer/MT",
    buyAmt: "INR 0.00",
    sell: "Best Seller/MT",
    sellAmt: "INR 0.00",
    last: "Last Match",
    lastAmt: "INR 0.00",
  },
  {
    id: 2,
    idTag: "USAGUJ",
    name: "RB2 | 52 FC +/- 1 - CFR",
    icon: <i class="devicon-react-original colored"></i>,
    country: "Peru",
    weight: "10382GAD(Kcal/Kg)",
    buy: "Best Buyer/MT",
    buyAmt: "INR 0.00",
    sell: "Best Seller/MT",
    sellAmt: "INR 0.00",
    last: "Last Match",
    lastAmt: "INR 0.00",
  },
  {
    id: 3,
    idTag: "USAGUJ",
    name: "ANTHRACITE PERU",
    icon: <i class="devicon-react-original colored"></i>,
    country: "Peru",
    weight: "10382GAD(Kcal/Kg)",
    buy: "Best Buyer/MT",
    buyAmt: "INR 0.00",
    sell: "Best Seller/MT",
    sellAmt: "INR 0.00",
    last: "Last Match",
    lastAmt: "INR 0.00",
  },
  {
    id: 4,
    idTag: "ENNKAPT",
    name: "ANTHRACITE PERU",
    icon: <i class="devicon-react-original colored"></i>,
    country: "Peru",
    weight: "10382GAD(Kcal/Kg)",
    buy: "Best Buyer/MT",
    buyAmt: "INR 0.00",
    sell: "Best Seller/MT",
    sellAmt: "INR 0.00",
    last: "Last Match",
    lastAmt: "INR 0.00",
  },
  {
    id: 5,
    idTag: "ENNKAPT",
    name: "ANTHRACITE PERU",
    icon: <i class="devicon-react-original colored"></i>,
    country: "Peru",
    weight: "10382GAD(Kcal/Kg)",
    buy: "Best Buyer/MT",
    buyAmt: "INR 0.00",
    sell: "Best Seller/MT",
    sellAmt: "INR 0.00",
    last: "Last Match",
    lastAmt: "INR 0.00",
  },
  {
    id: 6,
    idTag: "HALDIPT",
    name: "ANTHRACITE PERU",
    icon: <i class="devicon-react-original colored"></i>,
    country: "Peru",
    weight: "10382GAD(Kcal/Kg)",
    buy: "Best Buyer/MT",
    buyAmt: "INR 0.00",
    sell: "Best Seller/MT",
    sellAmt: "INR 0.00",
    last: "Last Match",
    lastAmt: "INR 0.00",
  },
  {
    id: 7,
    idTag: "HALDIPT",
    name: "ANTHRACITE PERU",
    icon: <i class="devicon-react-original colored"></i>,
    country: "Peru",
    weight: "10382GAD(Kcal/Kg)",
    buy: "Best Buyer/MT",
    buyAmt: "INR 0.00",
    sell: "Best Seller/MT",
    sellAmt: "INR 0.00",
    last: "Last Match",
    lastAmt: "INR 0.00",
  },
  {
    id: 8,
    idTag: "HALDIPT",
    name: "ANTHRACITE PERU",
    icon: <i class="devicon-react-original colored"></i>,
    country: "Peru",
    weight: "10382GAD(Kcal/Kg)",
    buy: "Best Buyer/MT",
    buyAmt: "INR 0.00",
    sell: "Best Seller/MT",
    sellAmt: "INR 0.00",
    last: "Last Match",
    lastAmt: "INR 0.00",
  },
  {
    id: 9,
    idTag: "INDOGUJ",
    name: "ANTHRACITE PERU",
    icon: <i class="devicon-react-original colored"></i>,
    country: "Peru",
    weight: "10382GAD(Kcal/Kg)",
    buy: "Best Buyer/MT",
    buyAmt: "INR 0.00",
    sell: "Best Seller/MT",
    sellAmt: "INR 0.00",
    last: "Last Match",
    lastAmt: "INR 0.00",
  },
  {
    id: 10,
    idTag: "INDOGUJ",
    name: "ANTHRACITE PERU",
    icon: <i class="devicon-react-original colored"></i>,
    country: "Peru",
    weight: "10382GAD(Kcal/Kg)",
    buy: "Best Buyer/MT",
    buyAmt: "INR 0.00",
    sell: "Best Seller/MT",
    sellAmt: "INR 0.00",
    last: "Last Match",
    lastAmt: "INR 0.00",
  },
  {
    id: 11,
    idTag: "INDOGUJ",
    name: "ANTHRACITE PERU",
    icon: <i class="devicon-react-original colored"></i>,
    country: "Peru",
    weight: "10382GAD(Kcal/Kg)",
    buy: "Best Buyer/MT",
    buyAmt: "INR 0.00",
    sell: "Best Seller/MT",
    sellAmt: "INR 0.00",
    last: "Last Match",
    lastAmt: "INR 0.00",
  },
  {
    id: 12,
    idTag: "HAZMAG",
    name: "ANTHRACITE PERU",
    icon: <i class="devicon-react-original colored"></i>,
    country: "Peru",
    weight: "10382GAD(Kcal/Kg)",
    buy: "Best Buyer/MT",
    buyAmt: "INR 0.00",
    sell: "Best Seller/MT",
    sellAmt: "INR 0.00",
    last: "Last Match",
    lastAmt: "INR 0.00",
  },
  {
    id: 13,
    idTag: "HAZMAG",
    name: "ANTHRACITE PERU",
    icon: <i class="devicon-react-original colored"></i>,
    country: "Peru",
    weight: "10382GAD(Kcal/Kg)",
    buy: "Best Buyer/MT",
    buyAmt: "INR 0.00",
    sell: "Best Seller/MT",
    sellAmt: "INR 0.00",
    last: "Last Match",
    lastAmt: "INR 0.00",
  },
  {
    id: 14,
    idTag: "HAZMAG",
    name: "ANTHRACITE PERU",
    icon: <i class="devicon-react-original colored"></i>,
    country: "Peru",
    weight: "10382GAD(Kcal/Kg)",
    buy: "Best Buyer/MT",
    buyAmt: "INR 0.00",
    sell: "Best Seller/MT",
    sellAmt: "INR 0.00",
    last: "Last Match",
    lastAmt: "INR 0.00",
  },
];
